version: 2
workflows:
  version: 2
  ruby:
    jobs:
      - ruby-25-showcase
      - ruby-24-showcase
      - ruby-23-showcase
      - ruby-showcase-baseline
jobs:
  ruby-showcase-baseline:
    docker:
      - image: java:8
    working_directory: /gapic-generator
    steps:
      - checkout
      - run:
          name: Download and install protoc.
          command: |
            curl -o ~/protoc.zip -L \
              https://github.com/google/protobuf/releases/download/v3.6.0/protoc-3.6.0-linux-x86_64.zip
            unzip ~/protoc.zip -d ~/protoc
            mv ~/protoc/bin/* /usr/local/bin/
            mv ~/protoc/include/* /usr/local/include/
      - run:
          name: Run generation script.
          command: ./showcase/ruby/generate.sh
      - run:
          name: Check if generation script caused any changes.
          command: git status -s && git diff-index --quiet HEAD

  ruby-25-showcase:
    docker:
      - image: ruby:2.5
      - image: landrito/gapic-showcase:pre-alpha
    working_directory: /gapic-generator
    steps:
      - checkout
      - run:
          name: Install dependencies.
          command: cd showcase/ruby && git init && bundle install
      - run:
          name: Run Ruby Showcase Tests.
          command: cd showcase/ruby && bundle exec rake test

  ruby-24-showcase:
    docker:
      - image: ruby:2.4
      - image: landrito/gapic-showcase:pre-alpha
    working_directory: /gapic-generator
    steps:
      - checkout
      - run:
          name: Install dependencies.
          command: cd showcase/ruby && git init && bundle install
      - run:
          name: Run Ruby Showcase Tests.
          command: cd showcase/ruby && bundle exec rake test

  ruby-23-showcase:
    docker:
      - image: ruby:2.3
      - image: landrito/gapic-showcase:pre-alpha
    working_directory: /gapic-generator
    steps:
      - checkout
      - run:
          name: Install dependencies.
          command: cd showcase/ruby && git init && bundle install
      - run:
          name: Run Ruby Showcase Tests.
          command: cd showcase/ruby && bundle exec rake test
