version: 2
workflows:
  version: 2
  ruby:
    jobs:
      - ruby-showcase-baseline
      - ruby-25-showcase-unit-tests:
          requires:
            - ruby-showcase-baseline
      - ruby-25-showcase-integration-tests:
          requires:
            - ruby-25-showcase-unit-tests

jobs:
  ruby-showcase-baseline:
    docker:
      - image: java:8
    working_directory: /gapic-generator
    steps:
      - checkout
      - run:
          name: Run generation
          command: ./gradlew updateRubyShowcase
      - run:
          name: Check if generation caused any changes
          command: |
            git diff-index -p HEAD -- showcase/ruby
            git diff-index -p HEAD -- showcase/ruby | test -z

  ruby-25-showcase-unit-tests:
    docker:
      - image: ruby:2.5
    working_directory: /gapic-generator
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd showcase/ruby && git init && bundle install
      - run:
          name: Run Generated Tests
          command: cd showcase/ruby && bundle exec rake test

  ruby-25-showcase-integration-tests:
    docker:
      - image: ruby:2.5
      - image: landrito/gapic-showcase:pre-alpha
    working_directory: /gapic-generator
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd showcase/ruby-integration-tests && bundle install
      - run:
          name: Run Integration Tests
          command: cd showcase/ruby-integration-tests && bundle exec rake test

