version: 2.0

anchor_generate_language: &anchor_generate_language
  # We will set the GENERATE_LANGUAGE var right before each invocation
  # of this command in order to specify which language to generate.
  command: |
    cd gapic-generator
    python gapic_smoketest.py \
        --user-config=.circleci/artman_config.yaml \
        --log=/tmp/workspace/reports/smoketest.log \
        ${GENERATE_LANGUAGE}
    # Get the exit code from the python script
    retVal=$?
    if [ $retVal -eq 0 ]; then
      # If language client generation succeeded,
      # create a file in REPORTS_DIR just as a signal of success.
      # The `verify-[lang]-generation` job will check for existence of that file to
      # determine whether or not to kick off a `test-[lang]` job.
      touch ${REPORTS_DIR}/${GENERATE_LANGUAGE}.log
    fi

anchor_check_generation: &anchor_check_generation
  command: |
    # GENERATE_LANGUAGE must be set to a language string (e.g. "java") beforehand.
    if [ -e /tmp/workspace/reports/${$GENERATE_LANGUAGE}.log ]
    then
        exit 0
    else
        exit 1
    fi

# We use this setup for jobs that verify that generation of a given language succeeded.
anchor_verify_generation: &anchor_verify_generation
  working_directory: /tmp/
  docker:
    - image: circleci/cci-demo-docker
  steps:
    - attach_workspace:
        # Load the REPORTS_DIR from generate-clients
        at: workspace
    - run:
        name: Check if language generation had succeeded.
        <<: *anchor_check_generation

# This command is called for each API that we run python nox tests on.
anchor_test_python: &anchor_test_python
  command: |
    cd workspace/gapic-generator/artman-genfiles/python/${TEST_API}
    nox --session "unit(py='2.7')"
    nox --session "unit(py='3.5')"
    nox --session "unit(py='3.6')"
    # python3.7 isn't installed on this Docker image yet, so we can't test against 3.7.
    # https://github.com/googleapis/gapic-generator/issues/2208
  when: always



jobs:
  build:
    docker:
      - image: googleapis/git
    steps:
      - checkout
    working_directory: /tmp/workspace/gapic-generator
  install-gapic-generator:
    docker:
      - image: circleci/java:8-jdk
    working_directory: /tmp/workspace
    steps:
      - checkout:
          path: gapic-generator
      - run:
          name: Checkout googleapis
          command: |
            mkdir -p googleapis
            git clone https://github.com/googleapis/googleapis.git googleapis
      - run:
          name: Build and install local toolkit
          command: |
            export RUNNING_IN_ARTMAN_DOCKER=True
            rm -rf gapic-generator/.git/
            gapic-generator/gradlew -p gapic-generator fatJar createToolPaths install build -x test -x javadoc
      - persist_to_workspace:
          # Save the toolkit and googleapis installations in workspace for later CircleCI jobs.
          root: /tmp/workspace
          paths:
            - gapic-generator
            - googleapis
  generate-clients:
    docker:
      - image: googleapis/artman:0.14.3
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          # Use the workspace created in install-gapic-generator
          at: workspace
      - run:
          name: Make reports directory
          command: |
            mkdir -p reports
            export REPORTS_DIR=/tmp/workspace/reports
      - run:
          name: Prepare to generate all Java libraries
          command: export GENERATE_LANGUAGE=java
          when: always
      - run:
          name: Generate all Java libraries
          <<: *anchor_generate_language
          when: always
      - run:
          name: Prepare to generate all Python libraries
          command: export GENERATE_LANGUAGE=python
          when: always
      - run:
          name: Generate all Python libraries
          <<: *anchor_generate_language
          when: always
      - run:
          name: Prepare to generate all Python libraries
          command: export GENERATE_LANGUAGE=go
          when: always
      - run:
          name: Generate all Go libraries
          <<: *anchor_generate_language
          when: always
      # TODO: run tasks to generate all other languages
      - store_artifacts:
          path: /tmp/workspace/reports
      - store_artifacts:
          path: /tmp/workspace/gapic-generator/artman-genfiles
      - persist_to_workspace:
          # Save all generated directories in workspace for later CircleCI jobs.
          root: /tmp/workspace
          paths:
            - gapic-generator/artman-genfiles
            - reports
  verify-java-generation:
    <<: *anchor_verify_generation
    environment:
      GENERATION_LANGUAGE: java
  verify-python-generation:
    <<: *anchor_verify_generation
    environment:
      GENERATION_LANGUAGE: python
  verify-golang-generation:
    <<: *anchor_verify_generation
    environment:
      GENERATION_LANGUAGE: go
  # TODO: verify other language clients were generated.
  test-java:
    working_directory: /tmp/
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          # Use the workspace created in generate-clients
          at: workspace
      - run:
          name: Run all Java generated unit tests
          command: |
            cd workspace/gapic-generator/artman-genfiles/java
            ./gradlew build test
      - run:
          name: Save test results
          command: |
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} /tmp/workspace/reports/ \;
          when: always
      - store_test_results:
          path: /tmp/workspace/reports
      - store_artifacts:
          path: /tmp/workspace/reports
  test-python:
    working_directory: /tmp/
    docker:
      # Use Docker image version v0.17.0 because latest v0.18.2 is not compatible with `attach_workspace` step.
      - image: googleapis/nox:0.17.0
    steps:
      - attach_workspace:
          # Use the workspace created in generate-clients
          at: workspace
      # Generated Logging client is broken: https://github.com/googleapis/gapic-generator/issues/2209.
      - run:
          name: Prepare to run nox on pubsub
          command: echo 'export TEST_API="pubsub-v1"' >> $BASH_ENV
      - run:
          name: Run nox on pubsub
          <<: *anchor_test_python
      - run:
          name: Prepare to run nox on speech
          command: echo 'export TEST_API="speech-v1"' >> $BASH_ENV
      - run:
          name: Run nox on speech
          <<: *anchor_test_python

  test-golang:
    working_directory: /tmp/
    docker:
      - image: circleci/golang:1.10
    steps:
      - attach_workspace:
          # Use the workspace created in generate-clients
          at: workspace
      - run:
          name: Set up golang dev env.
          command: |
            mkdir go
            export GOPATH=/tmp/golang/go
            export PATH=$PATH:$GOPATH/bin
            go get -d cloud.google.com/go/...
            go get -u github.com/golang/protobuf/protoc-gen-go
            cd $GOPATH/src/cloud.google.com/go
      - run:
          name: Test first batch.
          command: |
            go list cloud.google.com/go/... | grep apiv | xargs go test
          when: always
      - run:
          name: Test second batch.
          command: |
            go test -short cloud.google.com/go/...
          when: always
  # TODO: test other language clients.

workflows:
  version: 2
  run_generated_tests:
    jobs:
      - install-gapic-generator
      - generate-clients:
          requires:
            - install-gapic-generator
      - verify-java-generation:
          requires:
            - generate-clients
      - verify-python-generation:
          requires:
            - generate-clients
      - verify-go-generation:
          requires:
            - generate-clients
      - test-java:
          requires:
            - verify-java-generation
      - test-python:
          requires:
            - verify-python-generation
      - test-golang:
          requires:
            - verify-golang-generation

machine:
  services:
    - docker