version: 2.0

jobs:
  build:
    docker:
      - image: googleapis/git
    steps:
      - checkout
    working_directory: /tmp/workspace/gapic-generator
  generate-clients:
    docker:
      - image: googleapis/artman:0.14.3
    working_directory: /tmp/workspace
    steps:
      - checkout:
          path: gapic-generator
      - run:
          name: Checkout googleapis
          command: |
            mkdir -p googleapis
            git clone https://github.com/googleapis/googleapis.git googleapis
      - run:
          name: Build and install local toolkit
          command: |
            export RUNNING_IN_ARTMAN_DOCKER=True
            rm -rf gapic-generator/.git/
            gapic-generator/gradlew -p gapic-generator fatJar createToolPaths install build -x test -x javadoc
      - run:
          name: Make reports directory
          command: mkdir -p reports
      - run:
          name: Generate all client libraries
          command: |
            cd gapic-generator
            python gapic_smoketest.py \
                --user-config=.circleci/artman_config.yaml \
                --log=/tmp/workspace/reports/smoketest.log
      - store_artifacts:
          path: /tmp/workspace/reports
      - store_artifacts:
          path: /tmp/workspace/gapic-generator/artman-genfiles
      - persist_to_workspace:
          # Save all generated directories in workspace for later CircleCI jobs.
          root: /tmp/workspace
          paths:
            - gapic-generator/artman-genfiles
  test-java:
    working_directory: /tmp/
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          # Use the workspace created in generate-clients
          at: workspace
      - run:
          name: Run all Java generated unit tests
          command: |
            cd workspace/gapic-generator/artman-genfiles/java
            ./gradlew build test
      - run:
          name: Save test results
          command: |
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} /tmp/workspace/reports/ \;
      - store_test_results:
          path: /tmp/workspace/reports
      - store_artifacts:
          path: /tmp/workspace/reports
  test-python:
    working_directory: /tmp/
    docker:
      # Use Docker image version v0.17.0 because latest v0.18.2 is not compatible with `attach_workspace` step.
      - image: googleapis/nox:0.17.0
    steps:
      # Generated Python Logging client is broken: https://github.com/googleapis/gapic-generator/issues/2209.
      - attach_workspace:
          # Use the workspace created in generate-clients
          at: workspace
      - run:
          name: Run nox on pubsub
          command: |
            cd workspace/gapic-generator/artman-genfiles/python/pubsub-v1
            nox --session "unit(py='2.7')"
            nox --session "unit(py='3.5')"
            nox --session "unit(py='3.6')"
            # python3.7 isn't installed on this Docker image yet, so we can't test against 3.7.
            # https://github.com/googleapis/gapic-generator/issues/2208
          when: always
      - run:
          name: Run nox on speech
          command: |
            cd workspace/gapic-generator/artman-genfiles/python/speech-v1
            nox --session "unit(py='2.7')"
            nox --session "unit(py='3.5')"
            nox --session "unit(py='3.6')"
            # TODO: set up credentials for system tests.
          when: always
  test-ruby:
    working_directory: /tmp/
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      # Generated Ruby Logging client is broken: https://github.com/googleapis/gapic-generator/issues/2204.
      - attach_workspace:
          # Use the workspace created in generate-clients
          at: workspace
      - run:
          name: Install Ruby client dependencies.
          command: |
            gem install bundler
            git clone https://github.com/GoogleCloudPlatform/google-cloud-ruby
            cd google-cloud-ruby
            bundle update
      - run:
          name: Test Pubsub.
          command: |
            cd workspace/gapic-generator/artman-genfiles/ruby/google-cloud-ruby/google-cloud-pubsub
            bundle update
            bundle exec rake test
          when: always
      - run:
          name: Test Speech.
          command: |
            cd workspace/gapic-generator/artman-genfiles/ruby/google-cloud-ruby/google-cloud-speech
            bundle update
            bundle exec rake test
          when: always
  test-golang:
    working_directory: /tmp/
    docker:
      - image: circleci/golang:1.10
    steps:
#      - attach_workspace:
#          # Use the workspace created in generate-clients
#          at: workspace
      - run:
          name: Set up golang dev env.
          command: |
            mkdir go
            export GOPATH=/tmp/golang/go
            export PATH=$PATH:$GOPATH/bin
            go get -d cloud.google.com/go/...
            go get -u github.com/golang/protobuf/protoc-gen-go
            cd $GOPATH/src/cloud.google.com/go
      - run:
          name: Test first batch.
          command: |
            go list cloud.google.com/go/... | grep apiv | xargs go test
          when: always
      - run:
          name: Test second batch.
          command: |
            go test -short cloud.google.com/go/...
          when: always

workflows:
  version: 2
  run_generated_tests:
    jobs:
#      - generate-clients
      - test-golang
#      - test-ruby:
#          requires:
#            - generate-clients
#      - test-java:
#          requires:
#            - generate-clients
#      - test-python:
#          requires:
#            - generate-clients

machine:
  services:
    - docker