version: 2.0

anchor_build: &anchor_build
  name: Build and install local toolkit
  command: |
    export RUNNING_IN_ARTMAN_DOCKER=True
    ./gradlew fatJar
    ./gradlew createToolPaths
    rm -rf /toolkit/.git/
    ./gradlew install build -x test
    export TOOLKIT_HOME=/gapic-generator

anchor_docker: &anchor_docker
  docker:
    - image: googleapis/artman:0.14.3
  working_directory: /gapic-generator

jobs:
  build:
    <<: *anchor_docker
    steps:
      - checkout
  install-toolkit:
    <<: *anchor_docker
    steps:
      - checkout
      - run:
          name: Checkout googleapis
          command: |
            git clone https://github.com/googleapis/googleapis.git /tmp/googleapis
      - run:
          name: Build and install local toolkit
          command: |
            export RUNNING_IN_ARTMAN_DOCKER=True
            ./gradlew fatJar
            ./gradlew createToolPaths
            rm -rf /toolkit/.git/
            ./gradlew install build -x test
            export TOOLKIT_HOME=/gapic-generator
            mkdir /tmp/reports
  test-java-pubsub:
    <<: *anchor_docker
    steps:
      - checkout
      - run:
          name: Generate and run Java unit tests for Pubsub
          command: |
            mkdir /tmp/reports
            python gapic_smoketest.py --user-config=artman_config.yaml java pubsub
  test-java-logging:
    <<: *anchor_docker
    steps:
      - checkout
      - run:
          name: Generate and run Java unit tests for Logging
          command: |
            mkdir /tmp/reports
            python gapic_smoketest.py --user-config=artman_config.yaml java logging
      - store_test_results:
          path: /tmp/reports
      - run:
          name: Check if generation script caused any changes.
          command: git status -s && git diff-index --quiet HEAD
  test-java-speech:
    <<: *anchor_docker
    steps:
      - checkout
      - run:
          name: Generate and run Java unit tests for Speech
          command: |
            mkdir /tmp/reports
            python gapic_smoketest.py --user-config=artman_config.yaml java speech
      - store_test_results:
          path: /tmp/reports
      - run:
          name: Check if generation script caused any changes.
          command: git status -s && git diff-index --quiet HEAD

workflows:
  version: 2
  run_generated_tests:
    jobs:
      - build
      - install-toolkit:
          requires:
            - build
      - test-java-pubsub:
          requires:
            - install-toolkit
      - test-java-logging:
          requires:
            - install-toolkit
      - test-java-speech:
          requires:
            - install-toolkit

machine:
  services:
    - docker
  docker_layer_caching: true