version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
    working_directory: /tmp/workspace/gapic-generator
  install-toolkit:
    docker:
#      - image: googleapis/artman:0.14.3
      - image: circleci/openjdk:8-jdk
    working_directory: /tmp/workspace
    steps:
      - checkout:
          path: gapic-generator
      - run:
          command: ls gapic-generator
#      - run:
#          name: Checkout googleapis
#          command: |
#            mkdir -p googleapis
#            git clone https://github.com/googleapis/googleapis.git googleapis
      - run:
          name: Build and install local toolkit
          command: |
            export RUNNING_IN_ARTMAN_DOCKER=True
            rm -rf gapic-generator/.git/
            gapic-generator/gradlew -p gapic-generator fatJar createToolPaths install build -x test
      - run:
          name: Make reports dir
          command: mkdir -p reports
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
#            - googleapis
            - gapic-generator
            - reports
  run-generated-tests:
    docker:
      - image: googleapis/artman:0.14.3
    environment:
      RUNNING_IN_ARTMAN_DOCKER: True
    working_directory: /tmp/
    parallelism: 3
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Generate and run Java unit tests for Pubsub
          command: |
            cd gapic-generator
            python gapic_smoketest.py --user-config=artman_config.yaml java pubsub
#      - run:
#          name: Generate and run Java unit tests for Logging
#          command: |
#            python gapic_smoketest.py --user-config=artman_config.yaml java logging
#      - run:
#          name: Generate and run Java unit tests for Speech
#          command: |
#            python gapic_smoketest.py --user-config=artman_config.yaml java speech
      - store_test_results:
          path: /tmp/workspace/reports
      - store_artifacts:
          path: /tmp/workspace/reports

workflows:
  version: 2
  run_generated_tests:
    jobs:
      - install-toolkit
      - run-generated-tests:
          requires:
            - install-toolkit

machine:
  services:
    - docker